name: Create release

on:
  push:
    tags:
    - 'v*'

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get release notes from tag message
        id: tag-message
        run: printf "::set-output name=body::%s\n" "$(git tag -l --format='%(contents)' ${{ github.ref }})"
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.tag-message.outputs.body }}
          draft: false
          prerelease: false

  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Set release version from tag name
      id: release-version
      env:
        REF: ${{ github.ref }}
      run: printf "__version__ = \"%s\"\n" "${REF/#refs\/tags\/v/}" > docopt_sh/version.py
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygments flit
        flit install
    - name: Build and publish
      env:
        FLIT_INDEX_URL: https://upload.pypi.org/legacy/
        FLIT_USERNAME: __token__
        FLIT_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        flit publish
